# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdc534c07704a0b9e906fe9ff47afb35287aedbc684c789317a1fc88096535727b495e697c39a174c8daaacffb25c45c9ba2dcfe3f10eecf4ce8618447a74d42

test:
  secret_key_base: 966632179e4eed87db0b8ff004b382bbe0a3855f2ef6aed11cb27434dc0824db13c94c771a20549744c949628172d68e0b90f5a19d046f58278f802847ffb559

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
